server:
  port: 9001

spring:
  application:
    name: user-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: promptforge
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  # This is a Base64 encoded secret key - In production, use environment variable
  access-token-expiration: 3600000    # 1 hour in milliseconds
  refresh-token-expiration: 86400000  # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.promptforge.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO