server:
  port: 9002

spring:
  application:
    name: prompt-service
    
  # PostgreSQL Configuration (metadata)
  datasource:
    url: jdbc:postgresql://localhost:5432/prompt_service_db
    username: promptforge
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  # MongoDB Configuration (with authentication)
  data:
    mongodb:
      uri: mongodb://promptforge:dev_password_123@localhost:27017/promptforge_db?authSource=promptforge_db

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.promptforge.prompt: DEBUG
    org.springframework.data.mongodb: DEBUG