server:
  port: 9003

spring:
  application:
    name: test-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test_service_db
    username: promptforge
    password: dev_password_123
  jpa:
    hibernate:
      ddl-auto: update