server:
  port: 9003

spring:
  application:
    name: test-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/test_service_db
    username: promptforge
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

# OpenAI Configuration (optional - will use Mock if not set)
openai:
  api:
    key: \

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.promptforge.test: DEBUG
    org.springframework.web: INFO