services:
  # PostgreSQL - Main relational database
  postgres:
    image: postgres:16-alpine
    container_name: promptforge-postgres
    environment:
      POSTGRES_USER: promptforge
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: promptforge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - promptforge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U promptforge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB - Document store for prompt versions
  mongodb:
    image: mongo:7
    container_name: promptforge-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: promptforge
      MONGO_INITDB_ROOT_PASSWORD: dev_password_123
      MONGO_INITDB_DATABASE: promptforge_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - promptforge-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - Caching & vector search
  redis:
    image: redis:7-alpine
    container_name: promptforge-redis
    command: redis-server --requirepass dev_password_123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - promptforge-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zookeeper - Required for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: promptforge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - promptforge-network

  # Kafka - Event streaming
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: promptforge-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - promptforge-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # pgAdmin - PostgreSQL UI (optional, for development)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: promptforge-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@promptforge.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - promptforge-network

  # Mongo Express - MongoDB UI (optional, for development)
  mongo-express:
    image: mongo-express:latest
    container_name: promptforge-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: promptforge
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev_password_123
      ME_CONFIG_MONGODB_URL: mongodb://promptforge:dev_password_123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - promptforge-network

  # RedisInsight - Official Redis GUI
  redisinsight:
    image: redis/redisinsight:latest
    container_name: promptforge-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis
    networks:
      - promptforge-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  redisinsight_data:

networks:
  promptforge-network:
    driver: bridge
