server:
  port: 9005

spring:
  application:
    name: analytics-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_service_db
    username: promptforge
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.promptforge.shared.event.UserRegisteredEvent

logging:
  level:
    com.promptforge.analytics: DEBUG
    org.springframework.kafka: INFO