server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
            - RewritePath=/api/users/(?<segment>.*), /users/${segment}

        # Prompt Service Routes
        - id: prompt-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/prompts/**
          filters:
            - RewritePath=/api/prompts/(?<segment>.*), /prompts/${segment}

        # Test Service Routes
        - id: test-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/tests/**
          filters:
            - RewritePath=/api/tests/(?<segment>.*), /tests/${segment}

        # Marketplace Service Routes
        - id: marketplace-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/marketplace/**
          filters:
            - RewritePath=/api/marketplace/(?<segment>.*), /marketplace/${segment}

        # Analytics Service Routes
        - id: analytics-service
          uri: http://localhost:9005
          predicates:
            - Path=/api/analytics/**
          filters:
            - RewritePath=/api/analytics/(?<segment>.*), /analytics/${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO