server:
  port: 9004

spring:
  application:
    name: marketplace-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace_service_db
    username: promptforge
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.promptforge.marketplace: DEBUG
    org.springframework.web: INFO